# Generated by Django 3.2.11 on 2022-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('grupo_prioritario', models.IntegerField(choices=[(1, 'Pessoas com 60 anos ou mais institucionalizadas'), (2, 'Pessoas com deficiencias institucionalizadas'), (3, 'Povos indígenas'), (4, 'Servidor público'), (5, 'Nenhuma das opções anteriores')], verbose_name='Prioridade')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('celular', models.CharField(max_length=15, verbose_name='Número do celular')),
                ('tipo_unidade', models.IntegerField(choices=[(1, 'CRAS'), (2, 'CREAS'), (3, 'CAPS'), (4, 'PROJETO LARA')], verbose_name='Tipo da unidade')),
                ('horario', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (14, 14), (15, 15), (16, 16)], verbose_name='Horário de atendimento')),
            ],
            options={
                'verbose_name': 'Atendimento agendado',
                'verbose_name_plural': 'Atendimentos agendados',
            },
        ),
    ]
